import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className='bg-[#2E3440] h-screen'>
      <Head>
        <title>Cesar Gomez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div className='w-screen h-screen bg-[#102026] flex flex-col justify-center px-[6rem]'>

      <h1 className='font-bold text-[42px] text-[#f2f2f2] my-[2rem]'>Hello,</h1>
      <p className='text-[16px] text-[#d9d9d9]'>thanks for your interest, im still working on my new personal website, it will be ready soon!</p>
      <p>&#128513;</p>
    </div>
      </div>
  )
}

export default Home
